default_config:

recorder:

input_boolean:
  heater_on:
    name: Heater toggle
  cooler_on:
    name: Cooler toggle
  window_open:
    name: Window
  window_open2:
    name: Window2

input_number:
  room_temp:
    name: Room Temperature
    initial: 20
    min: 16
    max: 30
    step: .5
    icon: mdi:home-thermometer

  room_floor_temp:
    name: Room Floor Temperature
    initial: 20
    min: 16
    max: 30
    step: .5
    icon: mdi:thermometer

  outside_temp:
    name: Outside Temperature
    initial: 20
    min: 0
    max: 30
    step: .5
    icon: mdi:thermometer-lines

sensor:
  - platform: template
    sensors:
      room_temp:
        value_template: "{{ states.input_number.room_temp.state | int | round(1) }}"
        entity_id: input_number.room_temp
      floor_temp:
        value_template: "{{ states.input_number.room_floor_temp.state | int | round(1) }}"
        entity_id: input_number.room_floor_temp

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state('input_boolean.heater_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.heater_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.heater_on

      cooler:
        value_template: "{{ is_state('input_boolean.cooler_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.cooler_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.cooler_on

      window:
        value_template: "{{ is_state('input_boolean.window_open', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.window_open
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.window_open

climate:
  - platform: dual_smart_thermostat
    name: Heat Cool Room
    heater: switch.heater
    cooler: switch.cooler
    openings:
     - input_boolean.window_open
     - input_boolean.window_open2
    target_sensor: sensor.room_temp
    floor_sensor: sensor.floor_temp
    min_temp: 15
    max_temp: 28
    target_temp: 23
    target_temp_high: 26
    target_temp_low: 23
    max_floor_temp: 28
    cold_tolerance: 0.3
    hot_tolerance: 0
    # min_cycle_duration:
    #   seconds: 5
    # keep_alive:
    #   minutes: 3
    initial_hvac_mode: "heat_cool"
    away_temp: 16
    precision: 0.1

  - platform: dual_smart_thermostat
    name: Heat Room
    heater: switch.heater
    target_sensor: sensor.room_temp
    floor_sensor: sensor.floor_temp
    openings:
      - input_boolean.window_open
      - input_boolean.window_open2
    min_temp: 15
    max_temp: 28
    target_temp: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

  - platform: dual_smart_thermostat
    name: Cool Room
    heater: switch.cooler
    ac_mode: true
    target_sensor: sensor.room_temp
    min_temp: 15
    max_temp: 28
    target_temp: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

logger:
  default: error
  logs:
    custom_components.dual_smart_thermostat: debug