default_config:

recorder:

input_boolean:
  heater_on:
    name: Heater toggle
  aux_heater_on:
    name: AUX Heater toggle
  cooler_on:
    name: Cooler toggle
  fan_on:
    name: Fan toggle
  dryer_on:
    name: Fan toggle
  heat_pump_cool:
    name: Heat Pump Heat toggle
  window_open:
    name: Window
  window_open2:
    name: Window2

input_number:
  room_temp:
    name: Room Temperature
    initial: 20
    min: 16
    max: 30
    step: .1
    icon: mdi:home-thermometer

  room_floor_temp:
    name: Room Floor Temperature
    initial: 20
    min: 16
    max: 30
    step: .1
    icon: mdi:thermometer

  outside_temp:
    name: Outside Temperature
    initial: 20
    min: 0
    max: 30
    step: .1
    icon: mdi:thermometer-lines

  humidity:
    name: humidity
    initial: 40
    min: 20
    max: 90
    step: .1
    icon: mdi:thermometer-water

sensor:
  - platform: template
    sensors:
      room_temp:
        value_template: "{{ states.input_number.room_temp.state | int | round(1) }}"
        entity_id: input_number.room_temp
      floor_temp:
        value_template: "{{ states.input_number.room_floor_temp.state | int | round(1) }}"
        entity_id: input_number.room_floor_temp
      outside_temp:
        value_template: "{{ states.input_number.outside_temp.state | int | round(1) }}"
        entity_id: input_number.outside_temp
      humidity:
        value_template: "{{ states.input_number.humidity.state | int | round(1) }}"
        entity_id: input_number.humidity

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state('input_boolean.heater_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.heater_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.heater_on

      aux_heater:
        value_template: "{{ is_state('input_boolean.aux_heater_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.aux_heater_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.aux_heater_on

      cooler:
        value_template: "{{ is_state('input_boolean.cooler_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.cooler_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.cooler_on

      fan:
        value_template: "{{ is_state('input_boolean.fan_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.fan_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.fan_on

      dryer:
        value_template: "{{ is_state('input_boolean.dryer_on', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.dryer_on
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.dryer_on

      heat_pump_cool:
        value_template: "{{ is_state('input_boolean.heat_pump_cool', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.heat_pump_cool
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.heat_pump_cool

      window:
        value_template: "{{ is_state('input_boolean.window_open', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.window_open
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.window_open

climate:
  - platform: dual_smart_thermostat
    name: Heat Cool Room
    unique_id: heat_cool_room
    heater: switch.heater
    cooler: switch.cooler
    openings:
     - input_boolean.window_open
     - input_boolean.window_open2
    target_sensor: sensor.room_temp
    floor_sensor: sensor.floor_temp
    min_temp: 15
    max_temp: 28
    target_temp: 23
    target_temp_high: 26
    target_temp_low: 23
    max_floor_temp: 28
    cold_tolerance: 0.3
    hot_tolerance: 0
    # min_cycle_duration:
    #   seconds: 5
    # keep_alive:
    #   minutes: 3
    heat_cool_mode: true
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

  # - platform: dual_smart_thermostat
  #   name: Heat Room
  #   unique_id: heat_room
  #   heater: switch.heater
  #   target_sensor: sensor.room_temp
  #   floor_sensor: sensor.floor_temp
  #   openings:
  #     - input_boolean.window_open
  #     - input_boolean.window_open2
  #   min_temp: 15
  #   max_temp: 28
  #   target_temp: 23
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0
  #   min_cycle_duration:
  #     seconds: 5
  #   keep_alive:
  #     minutes: 3
  #   # initial_hvac_mode: "off"
  #   away_temp: 16
  #   precision: 0.1

  # - platform: dual_smart_thermostat
  #   name: Cool Room
  #   unique_id: cool_room
  #   heater: switch.cooler
  #   ac_mode: true
  #   target_sensor: sensor.room_temp
  #   min_temp: 15
  #   max_temp: 28
  #   target_temp: 23
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0
  #   min_cycle_duration:
  #     seconds: 5
  #   keep_alive:
  #     minutes: 3
  #   # initial_hvac_mode: "off"
  #   away_temp: 16
  #   precision: 0.1

  # - platform: dual_smart_thermostat
  #   name: Edge Case 80
  #   unique_id: edge_case_80
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   #min_cycle_duration: 60
  #   precision: .5
  #   min_temp: 20
  #   max_temp: 25
  #   heat_cool_mode: true
  #   away:
  #     target_temp_low: 0
  #     target_temp_high: 50

  # - platform: dual_smart_thermostat
  #   name: Edge Case 150
  #   unique_id: edge_case_150
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   min_cycle_duration: 60
  #   precision: 1.0
  #   min_temp: 58
  #   max_temp: 80
  #   cold_tolerance: 1.0
  #   hot_tolerance: 1.0

  # - platform: dual_smart_thermostat
  #   name: Edge Case 155
  #   unique_id: edge_case_155
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   openings:
  #     - input_boolean.window_open
  #     - input_boolean.window_open2
  #   openings_scope:
  #     - heat
  #   min_temp: 18
  #   max_temp: 27
  #   target_temp: 23.0
  #   hot_tolerance: 0
  #   cold_tolerance: 0.20
  #   precision: 0.1
  #   target_temp_step: 0.5
  #   initial_hvac_mode: off

  # - platform: dual_smart_thermostat
  #   name: Edge Case 167
  #   unique_id: edge_case_167
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   min_temp: 55
  #   max_temp: 110
  #   heat_cool_mode: true
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0.3
  #   precision: 1.0

  # - platform: dual_smart_thermostat
  #   name: Edge Case 175
  #   unique_id: edge_case_175
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   heat_cool_mode: true
  #   fan: switch.fan
  #   fan_hot_tolerance: 1
  #   target_temp_step: 0.5
  #   min_temp: 9
  #   max_temp: 32
  #   target_temp: 19.5
  #   target_temp_high: 20.5
  #   target_temp_low: 19.5

  # - platform: dual_smart_thermostat
  #   name: Edge Case 178
  #   unique_id: edge_case_178
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   heat_cool_mode: true
  #   target_temp_step: 0.5
  #   min_temp: 9
  #   max_temp: 32
  #   target_temp: 19.5
  #   target_temp_high: 20.5
  #   target_temp_low: 19.5
  #   away:
  #     temperature: 12
  #     target_temp_low: 12
  #     target_temp_high: 22.5
  #   home:
  #     temperature: 20
  #     target_temp_low: 19
  #     target_temp_high: 20.5
  #   sleep:
  #     temperature: 17
  #     target_temp_low: 17
  #     target_temp_high: 21
  #   eco:
  #     temperature: 19
  #     target_temp_low: 19
  #     target_temp_high: 21.5

  # - platform: dual_smart_thermostat
  #   name: Edge Case 184
  #   unique_id: edge_case_184
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   fan: switch.fan
  #   target_sensor: sensor.room_temp
  #   min_temp: 60
  #   max_temp: 85
  #   fan_hot_tolerance: 0.5
  #   heat_cool_mode: true
  #   min_cycle_duration:
  #     seconds: 60
  #   keep_alive:
  #     minutes: 3
  #   away:
  #     target_temp_low: 68
  #     target_temp_high: 77
  #   home:
  #     target_temp_low: 71
  #     target_temp_high: 74
  #   precision: 0.1
  #   target_temp_step: 0.5

  # - platform: dual_smart_thermostat
  #   name: Edge Case 181
  #   unique_id: edge_case_181
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   fan: switch.fan
  #   target_sensor: sensor.room_temp
  #   floor_sensor: sensor.floor_temp
  #   heat_cool_mode: true
  #   max_floor_temp: 26
  #   min_floor_temp: 10
  #   fan_hot_tolerance: 0.7
  #   target_temp_step: 0.1
  #   precision: 0.1
  #   min_temp: 9
  #   max_temp: 32
  #   target_temp: 20
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0.3

  # - platform: dual_smart_thermostat
  #   name: Edge Case 239
  #   unique_id: edge_case_239
  #   heater: switch.heater
  #   # cooler: switch.cooler
  #   target_sensor: sensor.room_temp
  #   heat_cool_mode: false #true # <-important
  #   keep_alive: #lo attivo e commento initial_hvac_mode per verificare se mantiene lo stato al riavvio
  #     minutes: 2
  #   ac_mode: true
  #   min_temp: 16
  #   max_temp: 32
  #   cold_tolerance: 0.4
  #   hot_tolerance: 0.1
  #   target_temp_step: 0.1
  #   min_cycle_duration:
  #     minutes: 1
  #   away:
  #     temperature: 28.0
  #     target_temp_low: 27
  #     target_temp_high: 29.5
  #   home:
  #     temperature: 23.0
  #     target_temp_low: 22.5
  #     target_temp_high: 23.5
  #   comfort:
  #     temperature: 25.0
  #     target_temp_low: 24
  #     target_temp_high: 25.5
  #   sleep:
  #     temperature: 27.5
  #     target_temp_low: 26.5
  #     target_temp_high: 28.0

  - platform: dual_smart_thermostat
    name: Edge Case 307
    unique_id: edge_case_307
    heater: switch.heater
    cooler: switch.cooler
    target_sensor: sensor.room_temp
    min_temp: 15
    max_temp: 28
    target_temp: 24
    target_temp_high: 26.5
    target_temp_low: 24
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    away: # this preset will be available for all hvac modes
      temperature: 18
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 24
    precision: 0.1
    target_temp_step: 0.5
    keep_alive:
      minutes: 3

  # - platform: dual_smart_thermostat
  #   name: Edge Case 210
  #   unique_id: edge_case_210
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   fan: switch.fan
  #   target_sensor: sensor.room_temp
  #   heat_cool_mode: true
  #   min_temp: 60
  #   max_temp: 85
  #   fan_hot_tolerance: 0.5
  #   heat_cool_mode: true
  #   min_cycle_duration:
  #     seconds: 60
  #   keep_alive:
  #     minutes: 3
  #   away:
  #     target_temp_low: 68
  #     target_temp_high: 77
  #   home:
  #     target_temp_low: 71
  #     target_temp_high: 74
  #   precision: 0.1
  #   target_temp_step: 0.5

  # - platform: dual_smart_thermostat
  #   name: Edge Case 241
  #   unique_id: edge_case_241
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   fan: switch.fan
  #   target_sensor: sensor.room_temp
  #   heat_cool_mode: true # <-required
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0.2
  #   fan_hot_tolerance: 1
  #   target_temp_step: 0.5
  #   min_temp: 14
  #   max_temp: 28
  #   comfort:
  #     temperature: 21
  #     target_temp_low: 21
  #     target_temp_high: 21.5
  #   away:
  #     temperature: 21
  #     target_temp_low: 15
  #     target_temp_high: 28


  # - platform: dual_smart_thermostat
  #   name: Dual Humidity
  #   unique_id: dual_humidity
  #   heater: switch.heater
  #   cooler: switch.cooler
  #   dryer: switch.dryer
  #   target_sensor: sensor.room_temp
  #   humidity_sensor: sensor.humidity
  #   heat_cool_mode: true
  #   target_temp_step: 0.1
  #   sensor_stale_duration: "00:10"
  #   precision: 0.1
  #   min_temp: 9
  #   max_temp: 32
  #   target_temp: 20
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0.3
  #   away:
  #     target_temp_high: 30
  #     target_temp_low: 23
  #     humidity: 55
  #   sleep:
  #     target_temp_high: 26
  #     target_temp_low: 18
  #     humidity: 60

  # - platform: dual_smart_thermostat
  #   name: Dual Heat Pump
  #   unique_id: dual_heat_pump
  #   heater: switch.heater
  #   target_sensor: sensor.room_temp
  #   heat_pump_cooling: switch.heat_pump_cool
  #   heat_cool_mode: true
  #   target_temp_step: 0.1
  #   precision: 0.1
  #   min_temp: 9
  #   max_temp: 32
  #   target_temp: 20
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0.3


  # - platform: dual_smart_thermostat
  #   name: AUX Heat Room
  #   unique_id: aux_heat_room
  #   heater: switch.heater
  #   secondary_heater: switch.aux_heater
  #   secondary_heater_timeout: 00:00:15
  #   secondary_heater_dual_mode: true
  #   openings:
  #     - input_boolean.window_open
  #     - input_boolean.window_open2
  #   target_sensor: sensor.room_temp
  #   away:
  #     temperature: 24
  #   anti_freeze:
  #     temperature: 10

  # - platform: dual_smart_thermostat
  #   name: FAN Cool Room
  #   unique_id: fan_cool_room
  #   heater: switch.heater
  #   fan: switch.fan
  #   fan_hot_tolerance: 2
  #   fan_on_with_ac: true
  #   ac_mode: true
  #   target_sensor: sensor.room_temp
  #   min_temp: 18
  #   max_temp: 25

  # - platform: dual_smart_thermostat
  #   name: FAN Only Room
  #   unique_id: fan_only_room
  #   heater: switch.fan
  #   fan_mode: true
  #   fan_hot_tolerance: 2
  #   fan_on_with_ac: true
  #   target_sensor: sensor.room_temp

  # - platform: generic_thermostat
  #   name: generic one
  #   unique_id: generic_cool
  #   heater: switch.cooler
  #   ac_mode: true
  #   target_sensor: sensor.room_temp
  #   min_temp: 15
  #   max_temp: 28
  #   target_temp: 23
  #   target_temp_high: 26
  #   target_temp_low: 23
  #   cold_tolerance: 0.3
  #   hot_tolerance: 0
  #   min_cycle_duration:
  #     seconds: 5
  #   keep_alive:
  #     minutes: 3
  #   # initial_hvac_mode: "off"
  #   away_temp: 16
  #   precision: 0.1

logger:
  default: error
  logs:
    custom_components.dual_smart_thermostat: debug

# debugpy: